name: Env Tests using Alpine

on:
  pull_request:
  push:
    branches: [master, develop]

jobs:
  build-core:
    runs-on: ubuntu-latest
    container: ocaml/opam2:alpine
    steps:
      - name: Adjust permissions
        run: |
          sudo chmod -R 777 . /github
          # github cache dir
          sudo mkdir -p /__w/
          sudo chmod -R 777 /__w/
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install missing packages
        uses: apk add --no-cache perl m4
      - name: Install submodules
        run: git submodule update --init --recursive
      - name: Install ocaml-tree-sitter
        run: eval $(opam env --root /home/opam/.opam --set-root) && ./install-scripts/install-ocaml-tree-sitter
      - name: Install pfff
        run: eval $(opam  env --root /home/opam/.opam --set-root) && opam install -y ./pfff
      - name: Install semgrep-core
        run: eval $(opam  env --root /home/opam/.opam --set-root) && cd semgrep-core && opam install --deps-only -y . && make all && make install
      - name: Upload semgrep-core
        run: |
          mkdir -p semgrep-files
          cp ./semgrep-core/_build/default/bin/Main.exe semgrep-files/semgrep-core
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: semgrep-core
          path: semgrep-files/semgrep-core
